### ISSUE TITLE
Link to UCWA helper library not working

### ISSUE THREAD

**Issue by fcipriani** [OfficeDev/skype-docs#102]
The link to download the samples and the UCWA helper libraries is giving ERR_INVALID_RESPONSE.

**Comment by JohnAustin-MSFT** [comment]
Can you point me to the page in the docs where you are seeing this problem?

**Comment by JohnAustin-MSFT** [comment]
Ok, found page. The fwlink for the JavaScript samples appears to be dead. I am investigating and will fix link to samples.
