### ISSUE TITLE
Documented response to GET Autodiscovery URL differs from actual response

### ISSUE THREAD

**Issue by jon-freed** [OfficeDev/skype-docs#105]
The page "Create an Application" ([at msdn.microsoft.com](https://msdn.microsoft.com/en-us/skype/ucwa/createanapplication) and [at GitHub](https://github.com/OfficeDev/skype-docs/blob/live/Skype/UCWA/CreateAnApplication.md)) currently has step 1 as "Send a GET request on the Autodiscovery URL", and step 2 as "Process the response from the previous request."

The page currently goes on to say the following about that response:

> The response from the previous GET request should be 200 OK. The body of the response contains three links. Each link is a key-value pair that consists of a name ("rel") and an object. The object is also a key-value pair in which the key is "href" and the value is the URL.
> - self (the current resource)
> - user (the user on whose behalf you are logging in)
> - xframe (the cross-domain frame used for web-based applications. )
> 
> The user and xframe URLs will be used later, so it is important that you cache them.

However, I just did such a GET, and the response I received does not match that description.  Here is what I received (with the actual domain name replaced with "MYDOMAIN"):

```
<resource xmlns="http://schemas.microsoft.com/rtc/2012/03/ucwa" rel="root" href="https://webdir0a.online.lync.com/Autodiscover/AutodiscoverService.svc/root?originalDomain=MYDOMAIN.com">
<link rel="xframe" href="https://webdir2a.online.lync.com/Autodiscover/AutodiscoverService.svc/root/xframe"/>
<link rel="redirect" href="https://webdir2a.online.lync.com/Autodiscover/AutodiscoverService.svc/root?originalDomain=MYDOMAIN.com"/>
</resource>
```

Is the documentation incorrect or out of date, or is there something else going on here?

Incidentally, the response has a certificate problem.  The response is being served from the address from step 1, e.g. https://lyncdiscover.MYDOMAIN.com.  But the certificate was issued to *.online.lync.com.

**Comment by kenakamu** [comment]
Sometimes response include user, otherwise redirect. When you get redirect, send Get request and you will get user link.
