### ISSUE TITLE
Error Docs Skype Web

### ISSUE THREAD

**Issue by alexisconia** [OfficeDev/skype-docs#108]
Hi,

I found a little mistake on the documentation page "[Developing Web SDK applications for Skype for Business Server](https://msdn.microsoft.com/fr-fr/skype/websdk/developforskypeforbusiness)".
The SignIn Manager is written with a lower i :

```
Skype.initialize({
  apiKey: 'a42fcebd-5b43-4b89-a065-74450fb91255' // SDK preview
}, api => {
  var app = new api.application;
  app.signinManager.signIn(...).then(() => {
    console.log("signed in as", app.personsAndGroupsManager.mePerson.displayName());
  }, err => {
    console.log("cannot sign in", err);
  });
}, err => {
  console.log("cannot download the SDK", err);
});
```

Regards,

**Comment by sidharthv** [comment]
Thanks for pointing that out. We will fix it.
