### ISSUE TITLE
Clarification in SignInManager.signIn method

### ISSUE THREAD

**Issue by ben-gilbert-smartsheet** [OfficeDev/skype-docs#109]
It would be really helpful to clarify something in the information about the signIn method here:
https://ucwa.skype.com/reference/WebSDK/interfaces/_s4b_sdk_d_.jcafe.signinmanager.html#signin

The text gives a set of examples of how to use signIn with different auth types (OAuth, IWA, login/password, etc.).  What it doesn't talk about is which of these auth types are actually supported with the different Skype for Business products.

For example, it is our understanding from some of the other help topics (like this one: https://msdn.microsoft.com/en-us/skype/websdk/developwebsdkappsforsfbonline) that for Skype for Business Online, OAuth is the preferred login type, and IWA is not supported with that product.

Would be great to clarify or link to another topic that explains which auth types makes sense based on the product type, and possibly which types are recommended.

Thanks!

**Comment by JohnAustin-MSFT** [comment]
Great feedback. I'll bring that to the developers who are responsible for the reference docs.

**Comment by sivijaya** [comment]
For Skype for Business Online OAuth is the only supported login type right now. That is why the article at https://msdn.microsoft.com/en-us/skype/websdk/developwebsdkappsforsfbonline uses only OAuth based sign in.
For Skype for Business On Premises there are a few auth types supported. These are explained in the documentation at https://msdn.microsoft.com/en-us/skype/websdk/developforskypeforbusiness
I'll update the second article to reflect that it is for Skype for Business onprem.
