### ISSUE TITLE
Question: Naming of OAuth HTML file for IE

### ISSUE THREAD

**Issue by ben-gilbert-smartsheet** [OfficeDev/skype-docs#110]
In [this section](https://msdn.microsoft.com/en-us/skype/websdk/developwebsdkappsforsfbonline#support-for-oauth2-in-internet-explorer) the requirement is stated for providing a static HTML resource that can be successful retrieved from the server.

The text says "You should use the client id GUID from the Azure app registration to name the folder". However, neither of the samples does this, and the OAuth process works fine in IE 11 if I just provide the address to a file with a simple name and no contents (e.g. https://mysite.com/path/emptyfile.htm).

Is there any reason not to just use a file with a simple name as above?  This will make configuration easier since we don't have to worry about using different GUIDs in the path for our different test and production environments.

**Comment by sidharthv** [comment]
It's ok to use any folder that is a sub folder of your base web site. Don't put the target html file in the same folder as an index.html file. So, for example, if my website is hosted at \SampleApp I would put my folder and empty html file under \SampleApp\Random\random.html.
I'll get the documentation on that page corrected.
