### ISSUE TITLE
Audio Conversation connecting timeout.

### ISSUE THREAD

**Issue by JammyT** [OfficeDev/skype-docs#117]
I use the SDK for audio conversation. On iOS 9.3 and above, cann't join meeting. 
This is alert info.
SfBAlert: type = 300, level = 0, error = "Error Domain=SfBErrorDomain Code=570621972 "(null)" UserInfo={Layer=TransportLayer, Component=ServerCommunication, ErrorNumber=20, SfBErrorSeverity=SfBErrorSeverityError}"
please help me.

**Comment by stewartadam** [comment]
Have you tried the tips from the following threads:
- https://github.com/OfficeDev/skype-ios-app-sdk-samples/issues/17
- https://github.com/OfficeDev/skype-ios-app-sdk-samples/issues/21
