### ISSUE TITLE
Documentation on the Trusted Application API

### ISSUE THREAD

**Issue by sjkp** [OfficeDev/skype-docs#119]
I saw the Ingite 2016 videos on the trusted application API. In them you say that it won't be ready until early 2017, but already now I can select the permissions in the old manage.windowsazure.com for my AD Application. 

I am able to obtain an access token using the app crendentials (client credential grant flow). However, when I try to access platformservice/v1/applications endpoint I get some strange internal server error telling me that application cannot be found. 

I don't know if I'm doing something wrong, as there's litteraly no documentation on the API, or whether it is simply not ready yet.

**Comment by JohnAustin-MSFT** [comment]
The Trusted Application API documentation is being written and will be available at the time the API is released.

**Comment by fabienvauchelles** [comment]
Hello @JohnAustin-MSFT,
do you have release date ? or a time horizon for the trusted api ?
Thanks !
Fabien.

**Comment by awaschick** [comment]
I am attempting to make sense of the preview version of the API, it's definitely still in early-adopter territory, but there is definitely a _very slim chance_ I will get it to work with my application any day now.

**Comment by sjkp** [comment]
I saw the MSDN docs was updated on the 16/2 does that mean the API is ready (I know it is still in preview).
