### ISSUE TITLE
CLA email address won't accept mail from outside microsoft.com

### ISSUE THREAD

**Issue by tomorgan** [OfficeDev/skype-docs#14]
The CLA submission address (officedev@microsoft.com) won't accept mail from any email address outside Microsoft. This means no-one can submit their CLA forms. :)  (email is referenced from here: https://github.com/OfficeDev/skype-docs)

Screenshot below, can forward full response if required.

![image](https://cloud.githubusercontent.com/assets/1378652/14119495/49607f68-f5e6-11e5-9c53-d3200a47294e.png)

**Comment by JohnAustin-MSFT** [comment]
Yes, unfortunately that is the case today. We will be opening the repo for submissions from outside of OfficeDev. I do not know when that will happen. I will amend the readme.md file to indicate the present restriction.

**Comment by JohnAustin-MSFT** [comment]
Hi Tom. We're working to get this issue resolved now.

**Comment by davidchesnut** [comment]
Hi Tom, I'm taking a look.

**Comment by davidchesnut** [comment]
@tomorgan we have confirmed the CLA you signed, so please go ahead and make your pull request. 
Thanks!
David
