### ISSUE TITLE
Anonymous meeting join - Skype for Business online

### ISSUE THREAD

**Issue by pavanrachapudy** [OfficeDev/skype-docs#142]
Is anonymous join now available for Skype for Business online version. Previously it was not as per my knowledge. But as per this link, I am assuming it is supported now. https://msdn.microsoft.com/en-us/library/office/mt670739(v=office.16).aspx

**Comment by JohnAustin-MSFT** [comment]
Anonymous meeting join is available from our Skype Web SDK public preview endpoint.

**Comment by pavanrachapudy** [comment]
I was trying to join the meeting url anonymously as per this example https://github.com/OfficeDev/skype-web-sdk-samples/blob/master/SkypeWebSDKOnlineSample/UI/samples/scripts/anonymous-join.js. It is still not going through for Skype for Business Online.
