### ISSUE TITLE
Duplicate Links rsc in myOnlineMeeting-ref

### ISSUE THREAD

**Issue by Herve-M** [OfficeDev/skype-docs#160]
Hello,

Little error on [skype-docs/Skype/UCWA/myOnlineMeeting_ref.md#links](myonlinemeeting_ref#links), `onlineMeetingExtensions` is set twice into `Links` rsc.

Herve-M

**Comment by Linda-Editor** [comment]
@Herve-M Finally fixed this two years later; changes will be live later today. Thanks for your contribution! https://docs.microsoft.com/en-us/skype-sdk/ucwa/myonlinemeeting_ref
