### ISSUE TITLE
UCWA access_token and signIn errors

### ISSUE THREAD

**Issue by peili** [OfficeDev/skype-docs#181]
How can we handle signIn errors using the SkypeWebSDK? 

If someone signs off on office.com, how do we know that the access token is not valid anymore?
Unfortunately we do not receive a silent error in a callback url.
Also see https://github.com/AzureAD/azure-activedirectory-library-for-js/issues/287 

Can we determine if a client has a valid access_token during SFB API initialization and signIn?
How can we manage long running sessions and API tokens? i.e. when I have left the page open overnight, how do I reestablish the session the next morning?

**Comment by baywet** [comment]
Same error here, it looks like half of the Open Id Connect silent sign-in flow is implemented.
Here is the error message we're getting
```
login_required (AADSTS50058: A silent sign-in request was sent but no user is signed in. The cookies used to represent the user's session were not sent in the request to Azure AD. This can happen if the user is using Internet Explorer or Edge, and the web app sending the silent sign-in request is in different IE security zone than the Azure AD endpoint (login.microsoftonline.com).
```
