### ISSUE TITLE
Error in example for Manage Devices

### ISSUE THREAD

**Issue by alexisconia** [OfficeDev/skype-docs#20]
There is a little error on this page https://msdn.microsoft.com/en-us/library/office/dn962193(v=office.16).aspx. In the javascript code for "Enumerating Available Devices" 

```javascript
for(var i = 0, i < client.devicesManager.cameras.length; i++) {
    var camera = client.devicesManager.cameras[i];
    console.log(camera.name());
}
```
In for instruction, there is a comma and not a semicolon

**Comment by JohnAustin-MSFT** [comment]
Hi Alexis, thanks for catching that.  I've corrected the problem in the markdown. The next publication to MSDN will show the correction.
