### ISSUE TITLE
Use SFB SDK in my enterprise app for chat service (messaging and presence as of now)

### ISSUE THREAD

**Issue by Vinodh-G** [OfficeDev/skype-docs#203]
Hi There,

We are planning the integrate iOS SFB SDK in my enterprise app for chat service (messaging and presence as of now) between users in community.

Can any one explain or route to a documentation what is the step by step procedure to register my enterprise app and use SFB App SDK service.

Once registration of my enterprise app is successful, what are the steps to achieve the below services from the App SDK.

1. My Enterprise app should be able to get all my conversation which is shown in SFB iOS App.
2. My Enterprise app should be able to get all the previous messages of a particular conversation(when ever I open a conversation in the new screen).
3. My Enterprise app should be able to send a message and should be able to get the participants status (online/offline/away)

I have checked the git samples (Banking App),  it fails when I Initiate  chat service or video call in BankingApp.

Thanks,
Vinodh

**Comment by alexisconia** [comment]
Hello,
All informations about App SDK are on MSDN (https://msdn.microsoft.com/en-us/skype/appsdk/skypeappsdk)
BankingApp needs configuration to work. All steps are listing on Github (in the App SDK repository)

For your information, as described on this webpage (https://msdn.microsoft.com/en-us/skype/appsdk/embedskypeb2ccomms), you can only use ios SDK for B2C scenarios where an anonymous user joins a SfB Meeting 
Regards

**Comment by Vinodh-G** [comment]
Thanks @alexisconia !!

So as per the above reply, I can make use of iOS SfB SDK in Client App,
- Join SfB meeting, provided you have a meeting URL
- Once user has joined the meeting, user can either have audio/video call or chat   

Kindly add if I have missed something ?

Second part of my query is,
As mentioned earlier we want to build a SfB backend for our iOS client App like, 
 -  Get all my conversation which is shown in SfB iOS App.
 -  Get all the previous messages of a particular conversation(whenever user open a conversation in the new screen).

I believe this is not possible only from the client iOS app. How much work would be involved from our App server side ? (since it would be talking to SfB server)

Could you please guide me with some reference, for the above mentioned queries ?

Thanks
