### ISSUE TITLE
Inconsistent link

### ISSUE THREAD

**Issue by ro31337** [OfficeDev/skype-docs#23]
![image](https://cloud.githubusercontent.com/assets/1477672/14827236/426df1c0-0b96-11e6-9aa7-b1e04a2bcf66.png)

Link "suggest changes" from MSDN [Skype Web SDK programming tasks](https://msdn.microsoft.com/en-us/library/office/dn962160(v=office.16).aspx) redirects to

```
https://github.com/OfficeDev/skype-docs/blob/master/ProgrammingTasks.md
```

(404 error on GitHub is displayed).

Correct link seems to be

```
https://github.com/OfficeDev/skype-docs/blob/master/Skype/WebSDK/ProgrammingTasks.md
```

**Comment by JohnAustin-MSFT** [comment]
Yes this is a known bug. We are working on a solution and should have a fix within a few days.

**Comment by JohnAustin-MSFT** [comment]
We've fixed it.  Try it now: https://msdn.microsoft.com/en-us/skype/websdk/programmingtasks

**Comment by kohlikohl** [comment]
The **suggest changes** link now redirects to
```
https://github.com/OfficeDev/skype-docs/blob/master/SkypeWebSDKPreview.md
```
which results in a 404 error on github :cry:

Additionally there are a bunch of links in
```
https://github.com/OfficeDev/skype-docs/blob/master/README.md
```
which point to a 404 ⛔ page currently.

![2016-06-06 16_05_27-skype-docs_readme md at master officedev_skype-docs](https://cloud.githubusercontent.com/assets/1196216/15826834/03288c6a-2c01-11e6-91eb-270559c48509.png)

**Comment by JohnAustin-MSFT** [comment]
All fixed.
