### ISSUE TITLE
Is there any limitation on callbackUrl (Trusted Application Api)?

### ISSUE THREAD

**Issue by tfischer** [OfficeDev/skype-docs#238]
I am trying to get the TrustedJoinMeeting sample to work, however, this line seems to throw an exception indicating that the callbackUrl is invalid:
  var invitation = await adhocMeeting.JoinAdhocMeetingAsync(null, loggingContext).ConfigureAwait(false);

The failing request and response is attached.
[adhocJoinFail2.txt](https://github.com/OfficeDev/skype-docs/files/867920/adhocJoinFail2.txt)

thanks,
Tom

**Comment by mateusfreira** [comment]
I had the same issue with this endpoint, neither "Reply URLs" nor "App ID URI" work as a value for this parameter.

**Comment by mateusfreira** [comment]
@tfischer Did you find out that is a valid value for callbackUrl?

**Comment by tfischer** [comment]
@mateusfreira Not yet.  However, it seems the callbackUrl must be in a 'verified custom domain', as indicated in the registration instructions (https://docs.microsoft.com/en-us/azure/active-directory/active-directory-add-domain).

Also, if you change the callback url, it is not sufficient to change it in azure portal->Reply URLs, you have to go back to the registration portal (https://skypeappregistration.azurewebsites.net/) and re-register it.

It is not completely clear that the callback endpoint doesn't have to do some work at the time of initial admin consent.  I am going through https://msdn.microsoft.com/en-us/office/office365/howto/building-service-apps-in-office-365 to check this.

There is also some more info here:
https://techcommunity.microsoft.com/t5/Skype-for-Business-IT-Pro/Calling-resources-on-Trusted-Application-API-for-Skype-Business

**Comment by tfischer** [comment]
I was finally able to get the callback working.  I configured the 'App ID URI' in Azure to be only a fqdn (no path and no port), eg 'https://my.domain.com' (not 'https://my.domain.com:443, not 'https://my.domain.com/callback').  I configured the callback uri to be the same exact string as my App ID URI.

**Comment by mateusfreira** [comment]
@tfischer Did you need to do something else to get this callback URI working? I did the same thing, and now I'm getting a new error? My callback URI is not even called once.

**Comment by tfischer** [comment]
You have to make sure the domain you are using for a callback is a verified custom domain in azure AD, have you done that?  If so, what is the error you are getting?  You can base-64 decode the X-MS-ClientDiagnostics to get more information on the error.

**Comment by mateusfreira** [comment]
I've done that,
It is the X-MS-ClientDiagnostics: (Decoded)
```
OperationContext-OutgoingHttpRequestExceptionMessage=Error on resolve DNS-ErrorCode=BadRequest-ErrorSubCode=CallbackUriUnreachable-ErrorDebugProperties=errorReportId="a43807d33fec450585accd6a279c5292"
-CorrelationId=2147489441-HttpMethod=POST-StatusCode=400-UriPath=/platformservice/v1/applications/2382007811/communication/audioVideoInvitations-UriQueryParameters=?modalities=AudioVideo&endpointId=sip:skypeforthewins1@tenfoldinc.onmicrosoft.com-UserAgent=skypeforthewins1-Latency=3155.5886-Timestamp=3/29/2017 12:44:23 AM-ClientId=db92ba7d-ab7d-4eb0-86e5-280b3717932a-ClientName=skype for the wins-EndpointId=sip:skypeforthewins1@tenfoldinc.onmicrosoft.com-TenantId=989d053a-e8ab-4800-a4da-dbbf03b43ccb-Machine=BL20R02FES04.infra.lync.com-FormatVersion=PlatformService 1.4-RequestedVersion=0-
```

**Comment by fabienvauchelles** [comment]
Hello,

We are blocked on this point too.

We have a verified domain. Our App Url Id and Callback Url Id are the same and registered with the  portal. Endpoint is found in the SFB user list.

However, when we speak with the bot. No callback is triggered. 

What did we missed ?

**Comment by fabienvauchelles** [comment]
Any tricks @tfischer ?
Thanks :)

**Comment by tfischer** [comment]
@fabienvauchelles I have not worked with this in a few months, but last I checked, inbound sessions to the bot were not working (see https://techcommunity.microsoft.com/t5/Skype-for-Business-IT-Pro/Inbound-call-for-endpoint-based-on-Trusted-Application-API-not/m-p/59557#M1502).  The bot could join conferences and establish outbound sessions though.  Not sure if that is working now.  This functionality seems to be working through Microsoft's bot builder, not sure if that is an option for you (https://blog.thoughtstuff.co.uk/2017/05/how-to-enable-your-bot-framework-bot-on-skype-for-business-and-how-i-finally-got-it-working/)

**Comment by fabienvauchelles** [comment]
@tfischer Yes it works with the BotFramework. However, it doesn't support HTML (planned for the month => https://github.com/Microsoft/BotBuilder/issues/2874).
Thanks for the answer.
Fabien.

**Comment by Githamza** [comment]
Have anybody found a solution for that ? I published a question on [stackoverflow ](https://stackoverflow.com/questions/51717271/microsoft-trusted-web-api-callback-unreachable)
