### ISSUE TITLE
Can not run the SkypeWebSDKOnlineSample login sample

### ISSUE THREAD

**Issue by zhangsichu** [OfficeDev/skype-docs#24]
Can not run the SkypeWebSDKOnlineSample login sample, can not get the token, or login

**Comment by zhangsichu** [comment]
can not get the token and use the metio.net domain.

**Comment by zhangsichu** [comment]
Downloading and setting up the samples.md,  can not use the "The developer sandbox", in the "https://ucwa.skype.com/" page, the My OAuth token button not works.

**Comment by JohnAustin-MSFT** [comment]
We will get on this right away. I apologize for the 5 day delay in response.

**Comment by srividhc** [comment]
Could you please provide a bit more information? I am checking the site now and I can see that it is bringing up My OAuth Tokens.
For example: Bearer cwt=AAEBHAEFAAAAAAAFFQAAAKuuXmvzGAIi1fxkebQLAACBENOUiS6FOltdmhThRmQXnQaCAtUogyDUg-Apd0hXTmppwOPJTGmhdI_sCWvDIDAYcUkdRqQQLYYIBUYTVgt00wgNEPafGCkKskFVn6NvOvBYlbY

**Comment by zhangsichu** [comment]
@JohnAustin-MSFT thanks a lot. @srividhc it works now, everything is correct, i can get my OAuth Tokens now, But i just get another issue, i can not send the message.

**Comment by zhangsichu** [comment]
![can_not_send_message](https://cloud.githubusercontent.com/assets/995849/15006237/30608904-1201-11e6-99de-a3ba59284cb8.png)
can not send the message

**Comment by srividhc** [comment]
Could you share your fiddler traces please? 
By the way, you could also post questions in stackoverflow with SkypeDeveloper tag
