### ISSUE TITLE
Trusted Application API AnonMeeting Sample Error

### ISSUE THREAD

**Issue by darroni** [OfficeDev/skype-docs#246]
401 (Unauthorized) error after deploying the sample as instructed.  Any thoughts?  
![image](https://cloud.githubusercontent.com/assets/17322676/24523279/663571e4-1547-11e7-8d7a-79b440e761d9.png)

**Comment by billy-clay-myers** [comment]
If you look to the bottom right it advises you that the Thumbprint used was not found. Make sure that you uploaded the certificate into the web app and that the thumbprint listed in the certificate management center for the web application lists the appropriate thumbprint and matches what you have entered into your code.

If you did not change the thumbprint in the code, check out the readme for the steps noted there and the fact that the cert needs to be a public cert.

Are you specifically trying to join an anon meeting or just verify that you can create them? If the latter or if you have not yet created an anonymous meeting , I suggest the remote advisor quick start which is a console application and will allow you to quickly verify that your tenant is configured appropriately.

**Comment by billy-clay-myers** [comment]
Note that even with the remote advisor quickstart that you will have to configure the appropriate settings from your azure portal application config

**Comment by darroni** [comment]
I've gone through simple console app.  Works great for me. 

For AnonMeeting sample, I've acquired a public cert through internal means for my URL (vhcare.cloudapp.net).  I've validated certificate assigned to FrontEnd_ Web site on CloudService VM:
![image](https://cloud.githubusercontent.com/assets/17322676/24523648/9beb87e6-1548-11e7-9d01-f47c21dee3ce.png)
and in Azure Cloud Service configuration/certificates:
![image](https://cloud.githubusercontent.com/assets/17322676/24523896/7f54b124-1549-11e7-88dc-0d44cd7f1208.png)
I've validated in code (ServiceConfiguration.Prod.cscfg):
![image](https://cloud.githubusercontent.com/assets/17322676/24523715/d80db244-1548-11e7-95eb-6233dac0afc0.png)
(ServiceDefinition.csdef):
![image](https://cloud.githubusercontent.com/assets/17322676/24523742/f5ad84e6-1548-11e7-90a0-c87e15c75ab7.png)
![image](https://cloud.githubusercontent.com/assets/17322676/24523762/096b491e-1549-11e7-9e98-a44db21eb91e.png)
And FrontEnd Web.Config:
![image](https://cloud.githubusercontent.com/assets/17322676/24523823/3a0d4e78-1549-11e7-80dc-f4d5e9aed964.png)

**Comment by harminderb** [comment]
Did you make sure to change the base.url in  AudienceUri, CallbackUriFormat, and ResourcesUriFormat to your specific cloudapp.net in the ServiceConfigurationProd.cscfg?

**Comment by darroni** [comment]
Yes I did.  Still same error:
![image](https://cloud.githubusercontent.com/assets/17322676/25105596/2d2d9e76-237a-11e7-8f03-c9e0fa0da61b.png)
Any help is appreciated.

**Comment by darroni** [comment]
Solved this problem by adding KeyCredentials information to the app manifest.  Followed these instructions:  

[https://github.com/Azure-Samples/active-directory-dotnet-daemon-certificate-credential/issues/29](url)
