### ISSUE TITLE
401 issue when sign in using oauth

### ISSUE THREAD

**Issue by wangpin34** [OfficeDev/skype-docs#257]
![image](https://cloud.githubusercontent.com/assets/12655367/24847801/ee6d95da-1df5-11e7-84c2-f7cf76d05b41.png)

sign code:
```javascript
  var config = {
   apiKey: 'a42fcebd-5b43-4b89-a065-74450fb91255', // SDK
   apiKeyCC: '9c967f6b-a846-4df2-b43d-5167e47d81e1' // SDK+UI
  }; 

  Skype.initialize({ apiKey: config.apiKey }, function (api) {
    var Application = api.application; // this is the Application constructor
    var app = new Application();

    app.signInManager.signIn ({
      client_id: 'c9271c87-06d6-4256-a091-2554eeb5291d',
      origins: [ 'https://webdir.online.lync.com/autodiscover/autodiscoverservice.svc/root'],
      cors: true,
      redirect_uri: 'http://localhost:8080/callback.html',
      version: 'skypesample',
    }).then(() => {
      console.log("signed in as", app.personsAndGroupsManager.mePerson.displayName());
    }, err => {
      console.log("cannot sign in", err);
    });
  }, function (err) {
    console.log("cannot load the sdk package", err);
  });
```

Azure configurations:
![image](https://cloud.githubusercontent.com/assets/12655367/24847831/29330452-1df6-11e7-8d07-51b89b0423c5.png)

![image](https://cloud.githubusercontent.com/assets/12655367/24847840/4244a69e-1df6-11e7-923f-4e87c1612633.png)

**Comment by luckyboykg** [comment]
Me too....

**Comment by wangpin34** [comment]
@luckyboykg 😞

**Comment by mashenoy** [comment]
@wangpin34 : From the screenshot, I can see you haven't given the Azure AD Application access to the Skype for Business API . 

Look at the delegated permissions in this article.

https://msdn.microsoft.com/en-us/skype/websdk/docs/troubleshooting/auth/aadauth-delegatepermissions

**Comment by wangpin34** [comment]
@mashenoy Thanks for your reply. Currently I only have Azure account for China which has no option to add Skype for Business API permission.  The sales from Azure told me that a global account is needed. So I will apply that in the future. 

Thanks you very much for the kindly reply.

**Comment by ravimandal47** [comment]
I am also receiving the same issue and I have already given Azure AD access to Skype for Business Online.
