### ISSUE TITLE
Failed to perform required BVD operation

### ISSUE THREAD

**Issue by kdilmurod** [OfficeDev/skype-docs#258]
Hi. I have error in
await applicationEndpoint.InitializeApplicationAsync(loggingContext).ConfigureAwait(false);

Error message:
{"code":"NotFound","message":"Failed to perform required BVD operation","debugInfo":{"errorReportId":"ca1dda343b374ef8ac9a149c1910957f"}}

StackTrace:
в Microsoft.SfB.PlatformService.SDK.ClientModel.BasePlatformResource2.<GetLatestPlatformServiceResourceAsync>d__361.MoveNext()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
в Microsoft.SfB.PlatformService.SDK.ClientModel.BasePlatformResource`2.d__33.MoveNext()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
в Microsoft.SfB.PlatformService.SDK.ClientModel.Discover.d__7.MoveNext()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
в Microsoft.SfB.PlatformService.SDK.ClientModel.ApplicationEndpoint.d__25.MoveNext()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
в System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
в TrustedJoinMeeting.TrustedJoinMeeting.d__1.MoveNext() в D:\Research\Skype\samples\QuickStartSamples\TrustedJoinMeeting\Program.cs:строка 65

**Comment by kdilmurod** [comment]
кто-то может помочь? что за BVD operation и что от меня требуется???

**Comment by kdilmurod** [comment]
Can someone help? What for BVD operation and what is required of me ???

**Comment by bobchow123** [comment]
Had you set up an endpoint? Please refer to the following for detail.
https://msdn.microsoft.com/en-us/skype/trusted-application-api/docs/trustedapplicationendpoint?f=255&MSPPError=-2147217396

After you set up an endpoint, you also need to update the ApplicationEndpointId in the corresponding configuration file.

**Comment by kdilmurod** [comment]
@bobchow123  
 I created a Trusted Application Endpoint and  the same error occurs. In #229 issue you are write call /platformService/v1/applications?endpointId=sip:sample@xxx.com. How did you call?


When in browser called https://api.skypeforbusiness.com/platformService/v1/applications?endpointId=sip:kdilmurodtester@jazzsofter.onmicrosoft.com
Goes error:
401 - Unauthorized: Access is denied due to invalid credentials.
You do not have permission to view this directory or page using the credentials that you supplied.

**Comment by bobchow123** [comment]
@kdilmurod It seem that you had not included the AAD(azure active directory) token in the header when calling the endpoint. If you use a browser to call the endpoint, you cannot include the **Authorization** in the header. Try [POSTMAN](https://www.getpostman.com/)
