### ISSUE TITLE
Only one server, "https://webdir1e.online.lync.com/" is correctly responding to oAuth flows.

### ISSUE THREAD

**Issue by nfplay** [OfficeDev/skype-docs#260]
Hi,

I have no problems getting into oAuth flow authentication regarding Skype SignIn when my home pool server is "https://webdir1e.online.lync.com/". All others - https://webdir2e.online.lync.com/, https://webdir0e.online.lync.com/, https://webdir0e.online.lync.com/, etc... - are returning 403 with "reason="Service does not allow a cross domain request from this origin."

The interactive web sdk page suffers from the same problem:
https://ucwa.skype.com/websdk

After choosing "Azure AD" authentication and filling my "Cliend ID" and including "https://ucwa.skype.com/websdk" in my App's Reply Url's, the demo only loads correctly if the home pool server is "https://webdir1e.online.lync.com/". For others, it keeps waiting forever.

This was working last week, any clue to what is happening?

Thanks in advance,

Nuno
![skype_error_1](https://cloud.githubusercontent.com/assets/5241920/24906729/dd8d353e-1eb0-11e7-85d9-14453f086abd.png)
![skype_error_2](https://cloud.githubusercontent.com/assets/5241920/24906728/dd8cc81a-1eb0-11e7-982a-df02492dff16.png)

**Comment by slavikko** [comment]
Can confirm, having the exact same issue.

**Comment by nfplay** [comment]
Can anyone help? @ajkher ? This is really starting to affect us...

**Comment by NeilLloydCloudInc** [comment]
This is also affecting us. Can we please have some indication as to when the problem might be resolved.

**Comment by ndquoc** [comment]
I debugged on Office 365 site and found a new URL to Auth: https://webpoolme1au103.infra.lync.com/Autodiscover/AutodiscoverService.svc/root

u replace this url to "origins" param when signin to skype:
 `  testForConfigAndSignIn({
                "client_id": "xxxxx-xxxx-xxxx-xxx-xxxx",
                "origins": ["https://webdir0f.online.lync.com/Autodiscover/AutodiscoverService.svc/root"],
                "cors": true,
                "version": 'myapp/1.0.0'
            });`

**Comment by nfplay** [comment]
I'm on Skype Online, so if i substitute the normal "https://**webdir**.online.lync.com/autodiscover/autodiscoverservice.svc/root" by the only server that's working "https://**webdir1e**.online.lync.com/Autodiscover/AutodiscoverService.svc/root" then it works. This "origins" parameter shouldn't be messed with in what concerns Skype Online:

This is quoted from "https://msdn.microsoft.com/en-us/skype/websdk/docs/developwebsdkappsforsfbonline":

The following example shows the parameters that are required when signing in to Skype for Business Online. 
Set the client_id parameter to the one that was auto generated for you in your Azure AD application. 
**Do not change the origins parameter.**
cors must be set to true. Without this being true you will encounter 403 errors like service does not allow cross domain requests from this origin when trying to perform auto discovery.
The redirect_uri parameter value in this sample is the URL of an empty html page in a folder below the web app folder. You can use any name for the folder and the file.
Provide an applicationame and version for your application.
app.signInManager.signIn({
     "client_id": "...",  // GUID obtained from Azure app registration.
     "origins": [ "https://webdir.online.lync.com/autodiscover/autodiscoverservice.svc/root" ],
     "cors": true, 
     "redirect_uri": '/an/empty/page.html',
     "version": '<YourAppName>/1.0.0.0'
});

But i guess i'll stick with it for the moment.

**Comment by nfplay** [comment]
Behavior is a little erratic though, sometimes the SDK enters in a loop trying to get, in my case, "https://webpooldb41e03.infra.lync.com/ucwa/oauth/v1/applications" saying "Application not found", several times, but not always. The service seems definitely unstable.

**Comment by pavanrachapudy** [comment]
For me it is not working in https://webdir.online.lync.com/autodiscover/autodiscoverservice.svc/root either.

**Comment by ericrrichards** [comment]
That's weird.  We tend to usually be webdir1b.online.lync.com, and haven't had any issues for the last couple of weeks.
