### ISSUE TITLE
Source Code used in Trusted Application API demo

### ISSUE THREAD

**Issue by bobchow123** [OfficeDev/skype-docs#263]
I had watched the Demo in [Dive deep on the new Trusted Application API for Skype for Business Online](https://channel9.msdn.com/Events/Ignite/2016/BRK4013-TS). In the video, there is a [website](http://sdksamplesucap.azurewebsites.net/) with a few demo. I would like to ask is the source code of the demo website in this repository?

Thanks

**Comment by sirLoaf** [comment]
+1
