### ISSUE TITLE
Error on Application Initialisation

### ISSUE THREAD

**Issue by rdunning-geo** [OfficeDev/skype-docs#274]
Hi,

We're currently working with the skype for business online trusted application api and have run into an issue when trying to start up our application endpoint. 
 
This was working fine untill about 11 am UTC +1 on Friday 24/04.
 
Having looked again this morning, it seems the response from https://api.skypeforbusiness.com/platformservice/discover returns a bad uri in the self link :
https://api.skypeforbusiness.com:4443/platformservice/discover
 
Not sure if this is the cause, but trying to return to that link times out.
 
I've attached our logs from our application attempting to establish the endpoint and a screenshot of the Get response from Discover.
[SFBApplicationInitialsiationIssue.txt](https://github.com/OfficeDev/skype-docs/files/952307/SFBApplicationInitialsiationIssue.txt)
![getrequesttodiscover](https://cloud.githubusercontent.com/assets/26873034/25345750/aac3ff4a-290d-11e7-9412-765db7c12236.PNG)

We've also attempted to use the sample apps and they no longer work

**Comment by subashsethy** [comment]
+1

**Comment by itisslizz** [comment]
+1

**Comment by sirLoaf** [comment]
+1

**Comment by rdunning-geo** [comment]
This was fixed by pre-release9
