### ISSUE TITLE
AnonMeetingJoinSamples

### ISSUE THREAD

**Issue by alexisconia** [OfficeDev/skype-docs#279]
Hi,
I get an error when i'm deploying Front End project in Azure. 
**Certificate with thumbprint ABCDEF1234567890ABCDEF1234567890ABCDEF12 not found in store**

It's the default value of the parameter "AppTokenCertThumbprint" in web.config.

There is no step in the deployment guide about certificate : https://github.com/OfficeDev/skype-docs/tree/live/Skype/Trusted-Application-API/samples/AnonMeetingJoinSamples

Thanks

**Comment by subashsethy** [comment]
You can use ADD_ClientSecret instead on thumbprint...Make sure you comment thumpPrint in web.config

**Comment by sirLoaf** [comment]
Hi,
check this md file -> [AADS2S](https://github.com/OfficeDev/skype-docs/blob/master/Skype/Trusted-Application-API/docs/AADS2S.md)
Then follow this guide -> [Building =365 Service](https://msdn.microsoft.com/en-us/office/office365/howto/building-service-apps-in-office-365?f=255&MSPPError=-2147217396)
And then you need to upload the certificate into the Certificate store in Azure (Cloud Service), copy the thumbprint and add it to your web.config and then you won't get this error any more.

**Comment by alexisconia** [comment]
Thanks!
