### ISSUE TITLE
IMBridge fails at Start chat

### ISSUE THREAD

**Issue by devsagaacc** [OfficeDev/skype-docs#286]
Hi,
Is there any documentation on setting up IMBridge sample?
I am getting "Failed to start chat service" when i click "Start chat"...

**Comment by itisslizz** [comment]
Same issue here. We receive the p2p token and can log in. We then get the conversation with the endpoint. If we check the state changes, we mostly get Created -> Connecting but never Connected. Therefore we cannot start the chatservice.

**Comment by sirLoaf** [comment]
+1

**Comment by devsagaacc** [comment]
Did you edit the WebsiteSamples\Samples\scripts\trustedappwebclient.js file?
It turns out that it works sometimes. Just refresh it until it opens up chat.

**Comment by humaruis** [comment]
Also encountered the same issue, below error will be thrown when get the conversation with the endpoint after sign in page with anonymous token for IMBridge case, appreciated if if somebody give me some suggestions.

{
    "code": "RequestFailed",
    "req": {
        "nobatch": true,
        "type": "POST",
        "url": "https://webpoolxxxxx.infra.lync.com/ucwa/psanon/v1/applications/112289910155/communication/messagingInvitations",
        "priority": 0,
        "headers": {
            "Accept": "application/json",
            "Content-Type": "application/json",
            "Authorization": "_Bearer psat=<hash:703:545ac4>",
            "X-Ms-Namespace": "internal",
            "X-MS-Correlation-Id": "1510261747",
            "Client-Request-Id": "WebSDK/1510261747",
            "X-Ms-SDK-Version": "SkypeWeb/0.4.499 master",
            "X-Ms-SDK-Session": "c92235222d689"
        }
    },
    "rsp": {
        "status": 403,
        "statusText": "Forbidden",
        "headers": {
            "X-Ms-Server-Fqdn": "DM20R04FES02.infra.lync.com",
            "Via": "1.1 DM20R04FES07.infra.lync.com RtcExt",
            "Client-Request-Id": "WebSDK/1510261747",
            "X-Ms-Client-Request-Id": "b236121d-bc77-4b15-94b9-ac62980dbc92",
            "Content-Length": "76",
            "Pragma": "no-cache",
            "X-Ms-Namespace": "internal",
            "Date": "Thu, 01 Jun 2017 08:20:27 GMT",
            "Content-Type": "application/json",
            "Cache-Control": "no-cache",
            "X-Ms-Correlation-Id": "ed19d9ec-97a1-46a4-af91-33b5123833a4, 8fe2d902-4ed4-40ed-9c87-f5914562ab95",
            "Expires": "-1"
        },
        "responseText": "{\"code\":\"Forbidden\",\"message\":\"The requested operation isn\\u0027t allowed.\"}",
        "data": {
            "code": "Forbidden",
            "message": "The requested operation isn't allowed."
        }
    }
}
