### ISSUE TITLE
Sharing controls are disabled by policy 

### ISSUE THREAD

**Issue by kdilmurod** [OfficeDev/skype-docs#293]
Hi, 
Generated adhocMeeting.JoinUrl  meeting disabled the share desktop button for anonym users, writed:
"Sharing controls are disabled by policy 
To share, ask someone in the meeting to make you a presenter, or sign in and rejoin the meeting."

Set-CsConferencingPolicy –Identity global –EnableAppDesktopSharing [Desktop | SingleApplication]
Does not help.
Do not tell me how to give access to enable the share desktop button?

![errskype](https://cloud.githubusercontent.com/assets/27182898/25891037/70a0c81c-3591-11e7-8d07-048d4ff06868.jpg)

**Comment by devsagaacc** [comment]
Hi,
Use this when creating adhoc meeting:
{
  "subject": "Meeting1",
  "accessLevel": "Everyone",
  "rel": "service:meeting",
  **"automaticLeaderAssignment": "Everyone"**
}
and everyone who joins will be able to share screen.

**Comment by kdilmurod** [comment]
Hi,
For create meeting I use 
Task<IAdhocMeeting> CreateAdhocMeetingAsync(AdhocMeetingCreationInput input, LoggingContext loggingContext = null)

where input parameters has string[] leaders.
AdhocMeetingCreationInput(string subject, AccessLevel accessLevel = AccessLevel.Everyone, string[] leaders = null)

Where can I pass the parameter **automaticLeaderAssignment**?

**Comment by devsagaacc** [comment]
I don't think you can add that parameter using the SDK.
You can read this tutorial https://blogs.msdn.microsoft.com/tsmatsuz/2017/04/13/skype-for-business-trusted-application-api-tutorial/ to see how to create meeting using post request.

**Comment by kdilmurod** [comment]
I am using TrustedJoinMeeting project in SDK  https://github.com/OfficeDev/skype-docs/tree/master/Skype/Trusted-Application-API/samples/QuickStartSamples

Is there no such possibility on this C# example?

**Comment by devsagaacc** [comment]
Looking at AdhocMeetingCreationInput i don't think there is.
Maybe you can try adding user to leaders list, and connecting as that user.

**Comment by kdilmurod** [comment]
When I set **leaders : new string[] { "AnonymName" }**   (AnonymName, Everyone, anonymmail@gmail.com, sip:anonymmail@gmail.com)
return
parameters":[{"name":"leaders","reason":"MissingOrInvalid"}]

**Comment by kdilmurod** [comment]
Thank you.  I resolve this problem
I am using old version create meeting...  In SDK using new version, where **AutomaticLeaderAssignment** does not.

            var meetConf = new AdhocMeetingInput();
            meetConf.AccessLevel = AccessLevel.Everyone;
            meetConf.AutomaticLeaderAssignment = AutomaticLeaderAssignment.Everyone;
            meetConf.Subject = Guid.NewGuid().ToString("N") + " test meeting";


            AdhocMeetingResource meeting = await applicationEndpoint.Application.GetAdhocMeetingResourceAsync(loggingContext, meetConf).ConfigureAwait(false);
