### ISSUE TITLE
WebSDK video call only works in edge

### ISSUE THREAD

**Issue by devsagaacc** [OfficeDev/skype-docs#294]
Hi,
WebSDK video call is not working in chrome or firefox, but works in edge.
Does anyone have any information about this?
Thanks

**Comment by billy-clay-myers** [comment]
Chrome works 70% of the time. This is a known issue.

Sent from my iPhone

On May 11, 2017, at 7:06 AM, devsagaacc <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,
WebSDK video call is not working in chrome or firefox, but works in edgde.
Does anyone have any information about this?
Thanks

**Comment by devsagaacc** [comment]
Are there any online samples where I can test it?

**Comment by sirLoaf** [comment]
It does not work anymore, it has been turned off by MSFT on their backend.
You can check their sandbox site: https://webrtcsandbox.azurewebsites.net/
It used to work there, but now its not anymore.
Console logs the following: "ActiveSpeaker video is not available anymore and has been turned off."

Firefox never worked at all

**Comment by sjkp** [comment]
Anyone know what status is on this, is video really not supposed to work. I was working in their build demos.

**Comment by billy-clay-myers** [comment]
It works in EDGE without a plugin.

It works in IE with the plugin. There is code specifically for plugin Detection for IE and Safari.

Chrome is pluginless as well but it is not production ready.

I am the guy that showed the app we have done for virtual visits in the Session at BUILD

Here is the javascript plugin  detection code that we use to detect the plugin or grab the links to download it:

var config = {
            apiKey: 'a42fcebd-5b43-4b89-a065-74450fb91255' // SDK
        };

Skype.initialize({ apiKey: config.apiKey },
                    function(api) {
                        window.skypeWebAppCtor = api.application;
                        window.skypeWebApp = new api.application();
                        client = window.skypeWebApp;
                        var isWebRtcSupported = client.devicesManager.mediaCapabilities.isBrowserMediaSupported();
                        if (!isWebRtcSupported) {
                            client.devicesManager.mediaCapabilities.isPluginInstalled.get()
                                .then(function(isInstalled) {
                                    $(".skype-plugin-status").removeClass("hidden");
                                    var pluginDownloadLinks =
                                        client.devicesManager.mediaCapabilities.pluginDownloadLinks();
                                    var pluginLink = ((window.navigator && window.navigator.platform) === 'Macintosh')
                                        ? pluginDownloadLinks[1]
                                        : pluginDownloadLinks[0];
                                    $(".plugin-link").attr("href", pluginLink);
                                    if (!isInstalled) {
                                        $(".skype-plugin-status").addClass("missing").removeClass("present");
                                        $("#installPlugin").show();
                                        $("#goAhead").hide();
                                    } else {
                                        $(".skype-plugin-status").addClass("present").removeClass("missing");
                                    }
                                });
                        } else {
                            $(".skype-plugin-status").addClass("hidden");
                        }
                    },
                    function(err) {
                        alert('some error occurred: ' + err);
                    });




Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
