### ISSUE TITLE
AutomaticLeaderAssignment property in new version AdhocMeetingCreationInput 

### ISSUE THREAD

**Issue by kdilmurod** [OfficeDev/skype-docs#300]
Hi,
@sankum-msft, @kohlikohl, @AasveenKaur @davnewman @ajkher can you add **AutomaticLeaderAssignment** property to **AdhocMeetingCreationInput** class? In #293 solution I can not use the new callback feature

public class AdhocMeetingCreationInput : IInput<AdhocMeetingInput>
{
    // Methods
    public AdhocMeetingCreationInput(string subject, AccessLevel accessLevel = 4, string[] leaders = null);
    internal override AdhocMeetingInput ToPlatformInput();

    // Properties
    public AccessLevel AccessLevel { [CompilerGenerated] get; }
    public string[] Leaders { [CompilerGenerated] get; }
    public string Subject { [CompilerGenerated] get; }
}

**Comment by sankum-msft** [comment]
Version [1.0.0-prerelease91](https://www.nuget.org/packages/Microsoft.SkypeforBusiness.TrustedApplicationAPI.SDK/1.0.0-prerelease91) of the SDK has been published to nuget.org addressing this.

**Comment by kdilmurod** [comment]
Thanks, @sankum-msft 

**await applicationEndpoint.InitializeApplicationAsync(loggingContext).ConfigureAwait(false);**
Now **after several** attempts it works without problems. 
Exception:

Microsoft.SfB.PlatformService.SDK.Common.RemotePlatformServiceException
   In Microsoft.SfB.PlatformService.SDK.ClientModel.BasePlatformResource`2. <GetLatestPlatformServiceResourceAsync> d__36`1.MoveNext ()
--- End tracing the stack from the previous location where the exception occurred ---
   In System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (Task task)
   In System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (Task task)
   In Microsoft.SfB.PlatformService.SDK.ClientModel.BasePlatformResource`2. <RefreshAsync> d__33.MoveNext ()
--- End tracing the stack from the previous location where the exception occurred ---
   In System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (Task task)
   In System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (Task task)
   In Microsoft.SfB.PlatformService.SDK.ClientModel.Applications. <RefreshAndInitializeAsync> d__4.MoveNext ()
--- End tracing the stack from the previous location where the exception occurred ---
   In System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (Task task)
   In System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (Task task)
   In Microsoft.SfB.PlatformService.SDK.ClientModel.Discover. <RefreshAndInitializeAsync> d__7.MoveNext ()
--- End tracing the stack from the previous location where the exception occurred ---
   In System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (Task task)
   In System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (Task task)
   In Microsoft.SfB.PlatformService.SDK.ClientModel.ApplicationEndpoint. <InitializeApplicationAsync> d__25.MoveNext ()
--- End tracing the stack from the previous location where the exception occurred ---
   In System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (Task task)
   In System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (Task task)
   In System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult ()
   In TrustedJoinMeeting.TrustedJoinMeeting. <RunAsync> d__1.MoveNext () in D: \ Research \ Skype \ samples \ QuickStartSamples \ TrustedJoinMeeting \ Program.cs: line 65
 HttpStatusCode InternalServerError

**Comment by sankum-msft** [comment]
If you have a repro, can you please share _X-Ms-Server-Fqdn_ and _Date_ response headers for the failing HTTP request so that I can investigate it? Thanks.

**Comment by kdilmurod** [comment]
Hi.
@sankum-msft can you add **ExpirationTime** param to new version? Now the default is 24 hours. It is not enough to hold a discussion on a big topic in the meeting. Thanks.

meetConf.ExpirationTime = DateTime.Now.AddMonth(1);
meetConf.MeetingType = MeetingType.Long;

At your request, I could not get X-Ms-Server-Fqdn...
