### ISSUE TITLE
android  SDK (1.0)- Skype for business 

### ISSUE THREAD

**Issue by ajanakievski** [OfficeDev/skype-docs#327]
Hello,

We are developing project for Vuzix glass m100 (android min SDK 15) that uses Skype for business SDK (current min SDK version is 17). We are banging our heads to find the old SDK (that supports min 15), however we could not find ANYTHING on net. 

I would appreciate if you can share any information on this, or point us to the right support microsoft team.

Best Regards, 
Alex.

**Comment by JohnAustin-MSFT** [comment]
Hi Alex,
As you've noticed, we are only keeping the current generally available SDK on the download page. Earlier versions of the SDK were preview. Preview SDKs are always replaced by GA SDKs when they are available.
John
