### ISSUE TITLE
WebSDK-Outbound Audio call from chrome takes 44s to establish (can repro in sample)

### ISSUE THREAD

**Issue by chrisbardon** [OfficeDev/skype-docs#343]
If you load the sample application from the prerelease branch and authenticate with Azure AD, p2p calls in chrome take around 44s to establish.  There just seems to be a really long delay before https://webpooldm10a26.infra.lync.com/ucwa/oauth/v1/applications/114028280811/communication/audioVideoInvitations is called.  Doesn't appear to happen in edge.

**Comment by billy-clay-myers** [comment]
As far as I know Chrome is not officially supported at this time. Video does not work at all. Audio works by chance

**Comment by JohnAustin-MSFT** [comment]
Hi Chris,
We have [limited support ](https://msdn.microsoft.com/en-us/skype/websdk/docs/apiproductkeys#supported-browsers)for Chrome. Unfortunately audio and video are not supported.
John
