### ISSUE TITLE
Skype password field in HE-Hebrew language seems like EN cursor

### ISSUE THREAD

**Issue by amirostro** [OfficeDev/skype-docs#344]
Hi Skype guys , 
Usually when inserting a password to a field , the cursor direction , at its top part , indication the language
chosen , so you won't be mistaken  while typing the characters, hidden by "*"
I this case only the email part is indicating the HE - Hebrew language cursor indication , and the password
field is not .
Thought maybe you would like to fix this in later versions.
![skype_password_he_no_cursor_indication_looks_like_en](https://user-images.githubusercontent.com/30312789/28407946-aad69450-6d3e-11e7-856c-ab4a8f27d694.JPG)

Shalom and Cheers , 
Amir

**Comment by JohnAustin-MSFT** [comment]
HI Amir,
That's great feedback!  The right place to give us this kind of feedback is in our [Skype for Business User Voice](https://www.skypefeedback.com/) channel.  
John
