### ISSUE TITLE
Is this SDK being managed ?

### ISSUE THREAD

**Issue by prabhakarreddy1234** [OfficeDev/skype-docs#345]
Is the Skype Web SDK being maintained by anyone ?  I don't see a response/comment to any of the issues.  Not sure if somebody is working on them or the issues doesn't make any sense to the developers.

**Comment by billy-clay-myers** [comment]
As far as I know Chrome is not officially supported at this time. Video does not work at all. Audio works by chance

**Comment by billy-clay-myers** [comment]
so it has GA'ed and tickets can be opened via Premier Support as far as I have been told

**Comment by prabhakarreddy1234** [comment]
Nice to know they have premier support. Can you give more details on it. Like their support plan, support email etc . I remember i looked for it but couldn't find.

Thanks

**Comment by billy-clay-myers** [comment]
I am getting that information myself and will share once I have it.

**Comment by prabhakarreddy1234** [comment]
That would be great. Thanks for your help with other issues.

**Comment by srividhc** [comment]
https://support.microsoft.com/en-us/gp/contactus81?Audience=Commercial
