### ISSUE TITLE
Silent Authentication without Microsoft Login page

### ISSUE THREAD

**Issue by prabhakarreddy1234** [OfficeDev/skype-docs#346]
Is there any way user can be authenticated silently with Azure AD without redirecting to microsoft login page? I can get access token through Graph API. I don't see any option to add this access token to Skype while authenticating against SfB Online.

**Comment by billy-clay-myers** [comment]
What are you trying to do? do you want them to interact with the controls and join meetings or are you trying to auth for something else?

if you want them to join and have video and audio, the answer is no. However you could use Anonymous join. Caveat, unless an authenticated person joins, the meeting is dead after 90 minutes of all anonymous people joined.

**Comment by prabhakarreddy1234** [comment]
We don't use Azure AD for authentication into our Web App. But SfB Online only supports Azure AD Authentication. So when the user ( authenticated with our Identity) tries to initiate a conference, he is being redirected to microsoft login page where he logs in and then he is able to interact with skype web sdk.  Participants can join anonymously. But Inviting person needs to be authenticated i guess. My question would be is there any way to skip microsoft login page ?

**Comment by billy-clay-myers** [comment]
so SfB Online supports full anonymous join. That is one of the major points of this SDK. You can register an app with azure AD which gives you key and secret that you can then use to authenticate and create adhoc meetings without ever going to the AD Page. we do this server side. You get a regular join link for meet.lync.com which could be emailed out and joined via the web client or you can build your own join page and embed the video.

**Comment by prabhakarreddy1234** [comment]
Good to know that. I am a bit confused about authentication.  Do you mind sharing the link of this content if you have. I am hoping to find more info on this. If your project is in github then please share it. I am sure it would give in depth understanding about this SDK.

**Comment by billy-clay-myers** [comment]
https://github.com/OfficeDev/skype-docs/tree/master/Skype/Trusted-Application-API/samples

check the quickstart sample that is just a console app which creates a meeting and gets the anonymous token.

**Comment by billy-clay-myers** [comment]
The package is available via nuget in Visual Studio. Remember to check the "Pre Release" box

**Comment by JohnAustin-MSFT** [comment]
Hi all,
I am going to close this issue since Billy has provided good answers + a link to the docs.
John
