### ISSUE TITLE
Generic Synchronous errors documentation needs associated https status code

### ISSUE THREAD

**Issue by baywet** [OfficeDev/skype-docs#370]
On this page of the documentation https://github.com/OfficeDev/skype-docs/blob/live/Skype/UCWA/GenericSynchronousErrors.md it'd be great to have a third column with the http status code which is associated with the error.
This way implementation on the client side and handling of those errors would be much easier.

**Comment by baywet** [comment]
To follow up on this issue, this page from the former documentation provides information that hasn't been reflected in the current documentation https://ucwa.skype.com/documentation/ProgrammingConcepts-Errors

**Comment by Linda-Editor** [comment]
@baywet I believe this is the page you are looking for: https://docs.microsoft.com/en-us/skype-sdk/ucwa/errorsandinformationalmessages

I'll add a link to this page from the GenericSynchronousErrors page too. Changes will be live later today.
