### ISSUE TITLE
TrustedAPI - Get Anon Token - Not working 

### ISSUE THREAD

**Issue by atanevski** [OfficeDev/skype-docs#377]
Hello,

I am trying to implement the Trusted API but its throwing exception that MeetingUrl is null (which is supposed to be null right?)

![image](https://user-images.githubusercontent.com/15204761/33366170-bcb615ce-d4ea-11e7-8221-2683171a343b.png)

This is code from the sample. sign-in.js line 117 where the body of the post is made and there is no meetingurl property

![image](https://user-images.githubusercontent.com/15204761/33367086-9751c62c-d4ed-11e7-9d63-2d62feca4c19.png)

And here is the exception (I haven't changed the code at all, this is "out-of-the-box")

Are there new updates that I need to make?

Thank you

**Comment by pavanrachapudy** [comment]
You need the meeting url to join the meeting.  https://msdn.microsoft.com/en-us/skype/trusted-application-api/docs/implementinganonymousclientwithskypewebsdk.
