### ISSUE TITLE
How can I use Skype Web SDK to connect a C# Bot (MS Bot Framework) to a SfB user?

### ISSUE THREAD

**Issue by vaditya04** [OfficeDev/skype-docs#64]
I have a chat bot which works in C# with the MS Bot Framework. I want to **initiate a connection** from that bot to a Skype for Business user.

The key points are:
1. I need SfB, not Skype
2. The bot has to connect to the Skype user, not the other way around
3. Bot can have a SfB account if necessary, which it will log into as though it were a real SfB user (need to know how to do this)

Will the Skype Web SDK be the correct tool to accomplish this?

Thanks!

**Comment by JohnAustin-MSFT** [comment]
Great question!  I will assign this issue to a platform team member for consideration.

**Comment by sidharthv** [comment]
Yes, this is possible using the Skype Web SDK. Like you mentioned, the bot will need to sign in to the S4B Web SDK using a S4B account.
Note that the Skype Web SDK is written using JavaScript. It will run in browser based environments or node.js. You may need additional work to communicate between the javascript of the Skype Web SDK and your C# code.
