### ISSUE TITLE
Isn't anonymous sign-in supported by SfB online?

### ISSUE THREAD

**Issue by ssenga** [OfficeDev/skype-docs#66]
I tried anonymous sign-in for SfB Online like below, the server responses '403 Forbidden'.

    window.skypeWebApp.signInManager.signIn({
        version:  config.version,
        client_id: '<client id>',
        cors: true,
        name: $('#name').text(),
        meeting: $('#meetingUri').text()
    }).then(function () {

So, I got a token from SfB Online server for anonymous meeting.

POST https://webdirjp1.online.lync.com/WebTicket/oauthtoken
> Accept:application/json
Content-Type:application/x-www-form-urlencoded;charset='utf-8'
Origin:https://dv-xxx-test03.azurewebsites.net
Referer:https://dv-xxx-test03.azurewebsites.net/htmlcontents/UI/index.html
Host:webdirjp1.online.lync.com
client_id:<client id>
>
grant_type=urn:microsoft.rtc:anonmeeting&password=XXXXXXX&ms_rtc_conferenceuri=sip:xxxxx@xxxxx.co.jp;gruu;opaque=app:conf:focus:id:XXXXXXX

The response was like
>
{
  "access_token": "cwt=AAID....7ubw",
  "expires_in": 3543,
  "token_type": "Bearer"
}

Then used the token for signin process like below.

    window.skypeWebApp.signInManager.signIn({
        version:  config.version,
        client_id: '<client id>',
        cors: true,
        name: $('#name').text(),
        origins: ["https://webdir.online.lync.com/autodiscover/autodiscoverservice.svc/root"],
        auth: function (request, sendRequest) {
            request.headers['Authorization'] = "Bearer AAID....7ubw";
            return sendRequest(request);
        }
    }).then(function () {

But the result was  '403 Forbidden', as well.

To clarify the reason, I sent a request to UCWA endpoint with a token which can be got like mentioned above. The response was also '403 Forbidden'.
![image](https://cloud.githubusercontent.com/assets/10590539/16661437/eadc488e-44ad-11e6-9e28-3aa7402c9694.png)

I cannot understand the behavior of SfB Online.
UCWA of Sfb Online itself doesn't support anonymous sign-in?

**Comment by JohnAustin-MSFT** [comment]
the documentation was incorrect. The Web SDK does not currently support signing in to an anonymous SfB online meeting. 
We have corrected the docs.
