### ISSUE TITLE
Error UCWA 2.0 documentation

### ISSUE THREAD

**Issue by alexisconia** [OfficeDev/skype-docs#74]
Hi,

I found a little mistake in the documentation [Authentication using Azure AD](https://msdn.microsoft.com/fr-fr/skype/ucwa/authenticationusingazuread) for UCWA 2.0.
The code below contains a comma after "Culture":"en-US"
```
POST https://webpoolXY.infra.lync.com/ucwa/oauth/v1/applications HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer <access-token>
...
{
 "UserAgent":"UCWA Samples",
 "EndpointId":"a917c6f4-976c-4cf3-847d-cdfffa28ccdf",
 "Culture":"en-US",
}
```

Regards

**Comment by JohnAustin-MSFT** [comment]
Thanks for finding this Alexis. I will take care of it...
