### ISSUE TITLE
Conversation metadata?

### ISSUE THREAD

**Issue by susangalbraith** [OfficeDev/skype-docs#86]
Is there a way when starting a conversation using the Skype Web SDK, to add in some metadata about the conversation?  We would use this to reference name of the application sending the conversation request, and also link to items in our application.  I see the conversation topic field, but we're looking for something where we'd be able to have more fields, and format the display of the data on the receiving end as well.

Thanks!
Susan

**Comment by sidharthv** [comment]
Hi Susan,

You can use 

```
chatService.start({
    context: 'contextual data. If it is not a primitive then it will be JSON stringified before sending to ucwa',
    contextType: 'some contenttype like text/plain but can pretty much be anything/anything, we simply pass it along to ucwa', // this is optional
    … other params
});
```
Hopefully this works for you.

Thanks
Sidharth

**Comment by sidharthv** [comment]
Hi Susan,

Please disregard my previous answer. That option is not documented and so not supported yet in production. Currently there isn't a way to do this with the SDK.

Thanks
Sidharth

**Comment by susangalbraith** [comment]
That explains why I couldn't get it working :)  Is there a plan to release support for this in the future?
