### ISSUE TITLE
Potentially inconsistent messaging for what APIs are available for what Skype for Business offering...

### ISSUE THREAD

**Issue by ChadJessup** [OfficeDev/skype-docs#90]
My company just moved to Skype for Business via Office 365, and I'm trying to get a feel for what APIs are available for the hosted SFB. There are quite a few names over the years for everything in the Skype ecosystem, so the confusion could easily just be on my end

At the top of the [UCWA 2.0](https://github.com/OfficeDev/skype-docs/blob/live/Skype/UCWA/UnifiedCommunicationsWebAPI2_0.md) doc, it states:

> Microsoft Unified Communications Web API 2.0 is a REST API that exposes **Skype for Business Server 2015** instant messaging (IM) and presence capabilities.

> Applies to: Skype for Business 2015, **Skype for Business Online**

And a little bit further down on the same document:
> **UCWA 2.0 is available only to customers who have an _on-premises_ deployment.**

On the [Skype Developer Platform page](https://github.com/OfficeDev/skype-docs/blob/live/Skype/SkypeDeveloperPlatform.md) the table states "Skype for Business Online" is available for this API.

I'm assuming that Skype for Business Server is on-premises, but Skype for Business Online is the Office 365 version, that is fully hosted by Microsoft?

**Comment by srividhc** [comment]
UCWA 2.0 is available for onprem and has been recently release (this April) for Skype for Business online. I have fixed the doc inconsistency.
